packages:
  - .

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
